config/routes.rb
CciHrProject::Application.routes.draw do 
  get "sessions/new"

  get "main/login"

  resources :users

  resources :webinars

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signout', :to => 'sessions#destroy'

  root :to => 'sessions#new'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :webinars, :uniq => true
  has_secure_password
  
  attr_accessible :name, :email, :admin, :password
  
  validates :name,  presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
end

app/models/webinar.rb
class Webinar < ActiveRecord::Base
  attr_accessible :title, :location, :date, :time, :description

  validates(:title, :presence => true)
  validates(:location, :presence => true)
  validates(:date, :presence => true)
  validates(:time, :presence => true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # Sign in user and redirect to user's show page. (users/:id)
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination' 
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/webinars_controller.rb
class WebinarsController < ApplicationController
  # GET /webinars
  # GET /webinars.json
  def index
    @webinars = Webinar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @webinars }
    end
  end

  # GET /webinars/1
  # GET /webinars/1.json
  def show
    @webinar = Webinar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @webinar }
    end
  end

  # GET /webinars/new
  # GET /webinars/new.json
  def new
    @webinar = Webinar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @webinar }
    end
  end

  # GET /webinars/1/edit
  def edit
    @webinar = Webinar.find(params[:id])
  end

  # POST /webinars
  # POST /webinars.json
  def create
    @webinar = Webinar.new(params[:webinar])

    respond_to do |format|
      if @webinar.save
        format.html { redirect_to @webinar, notice: 'Webinar was successfully created.' }
        format.json { render json: @webinar, status: :created, location: @webinar }
      else
        format.html { render action: "new" }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /webinars/1
  # PUT /webinars/1.json
  def update
    @webinar = Webinar.find(params[:id])

    respond_to do |format|
      if @webinar.update_attributes(params[:webinar])
        format.html { redirect_to @webinar, notice: 'Webinar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinars/1
  # DELETE /webinars/1.json
  def destroy
    @webinar = Webinar.find(params[:id])
    @webinar.destroy

    respond_to do |format|
      format.html { redirect_to webinars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webinars_helper.rb
module WebinarsHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title CCI Webinars  
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body

= yield

app/views/main/login.html.haml
%h1 CCI Webinars - Login
%p Email
= f.text_field :text
%p Password
= f.text_field :encrypted_password

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .container-fluid
    %form.form-stacked
      %fieldset
        %em
          #field
          .control-group
            = f.label :email, :class => 'control-label'
            .controls
              = f.text_field :email, :class => 'text_field'
          .control-group
            = f.label :name, :class => 'control-label'
            .controls
              = f.text_field :name, :class => 'text_field'
          .control-group
            = f.label :encrypted_password, :class => 'control-label'
            .controls
              = f.text_field :encrypted_password, :class => 'text_field'
          .control-group
            = f.label :admin, :class => 'control-label'
            .controls
              = f.check_box :admin, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = @user.class
.container-fluid
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
  %br
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User.new.class

.container-fluid
  %h1=t '.title', :default => model_class.model_name.human.pluralize
  %br
  %table.table.table-striped.table-bordered.span10
    %thead
      %tr
        %th= model_class.human_attribute_name(:name)
        %th= model_class.human_attribute_name(:email)
        %th= model_class.human_attribute_name(:encrypted_password)
        %th= model_class.human_attribute_name(:admin)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.encrypted_password
          %td= user.admin
          %td
            = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class =>  'btn btn-mini btn-info'
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
.container-fluid 
  = link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = @user.class
.container-fluid
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
  %br
= render :partial => "form"

app/views/users/show.html.haml
- model_class = @user.class

.container-fluid
  %h1=t '.title', :default => model_class.model_name.human
  %br
  .sidebar
  .content
    %p
      %strong= model_class.human_attribute_name(:name) + ':'
      %br
      = @user.name

    %p
      %strong= model_class.human_attribute_name(:email) + ':'
      %br
      = @user.email
      
    %p
      %strong= model_class.human_attribute_name(:encrypted_password) + ':'
      %br
      = @user.encrypted_password
    %p
      %strong= model_class.human_attribute_name(:admin) + ':'
      %br
      = @user.admin

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/webinars/_form.html.haml
= form_for @webinar, :html => { :class => 'form-horizontal' } do |f|
  .container-fluid
    %form.for-stacked
      %fieldset
        %em
          .control-group
            = f.label :title, :class => 'control-label'
            .controls
              = f.text_field :title, :class => 'text_field'
          .control-group
            = f.label :location, :class => 'control-label'
            .controls
              = f.text_field :location, :class => 'text_field'
          .control-group
            = f.label :time, :class => 'control-label'
            .controls
              = f.time_select :time, :class => 'time_select'
          .control-group
            = f.label :date, :class => 'control-label'
            .controls
              = f.date_select :date, :class => 'date_select'
          .control-group
            = f.label :description, :class => 'control-label'
            .controls
              = f.text_field :description, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), webinars_path, :class => 'btn'

app/views/webinars/edit.html.haml
- model_class = @webinar.class
.container-fluid
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
  %br
= render :partial => "form"

app/views/webinars/index.html.haml
- model_class = Webinar.new.class

.container-fluid
  %table.table.table-striped.table-bordered.span10
    %h1=t '.title', :default => model_class.model_name.human.pluralize
    %br
    %thead
      %tr
        %th= model_class.human_attribute_name(:title)
        %th= model_class.human_attribute_name(:location)
        %th= model_class.human_attribute_name(:time)
        %th= model_class.human_attribute_name(:date)
        %th= model_class.human_attribute_name(:description)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @webinars.each do |webinar|
        %tr
          %td= webinar.title
          %td Location
          %td= webinar.time
          %td= webinar.date
          %td= webinar.description
          %td
            = link_to t('.show', :default => t("helpers.links.show")), webinar_path(webinar), :class => 'btn btn-mini btn-info'
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_webinar_path(webinar), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), webinar_path(webinar), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

.container-fluid
  = link_to t('.new', :default => t("helpers.links.new")), new_webinar_path, :class => 'btn btn-primary'

app/views/webinars/new.html.haml
- model_class = @webinar.class
.container-fluid
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
  %br
= render :partial => "form"

app/views/webinars/show.html.haml
- model_class = @webinar.class

.container-fluid
  %h1=t '.title', :default => model_class.model_name.human
  %br
  .sidebar
  .content
    %p
      %strong= model_class.human_attribute_name(:title) + ':'
      %br
      = @webinar.title
    %p
      %strong= model_class.human_attribute_name(:location) + ':'
      %br
      = @webinar.location
    %p
      %strong= model_class.human_attribute_name(:time) + ':'
      %br
      = @webinar.time
    %p
      %strong= model_class.human_attribute_name(:date) + ':'
      %br
      = @webinar.date
    %p
      %strong= model_class.human_attribute_name(:description) + ':'
      %br
      = @webinar.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), webinars_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_webinar_path(@webinar), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), webinar_path(@webinar), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'